import { Employee, Project, Task, LeaveRequest, Expense, AuditLogEntry, Permission, CurrentUser } from './types';

export const PERMISSIONS_LIST: Permission[] = [
  { id: 'emp_read', name: 'View Employees', category: 'Employees', description: 'Access company directory and profiles' },
  { id: 'emp_write', name: 'Manage Employees', category: 'Employees', description: 'Add, update or terminate employee records' },
  { id: 'prj_read', name: 'View Projects', category: 'Projects', description: 'Inspect project roadmaps and milestones' },
  { id: 'prj_write', name: 'Manage Projects', category: 'Projects', description: 'Create projects, modify budgets and leads' },
  { id: 'tsk_manage', name: 'Manage Tasks', category: 'Projects', description: 'Assign tasks, edit priorities and deadlines' },
  { id: 'lev_request', name: 'Request Leave', category: 'Leaves', description: 'Submit personal annual, sick, or exceptional leaves' },
  { id: 'lev_approve', name: 'Approve Leaves', category: 'Leaves', description: 'Approve or reject team member leave submissions' },
  { id: 'exp_submit', name: 'Submit Expenses', category: 'Expenses', description: 'Submit reimbursement claims with receipts' },
  { id: 'exp_approve', name: 'Approve Expenses', category: 'Expenses', description: 'Review, approve, reject or request expense changes' },
  { id: 'aud_view', name: 'View Audit Logs', category: 'Audit', description: 'Inspect compliance logs and historical system actions' },
  { id: 'sys_admin', name: 'System Settings', category: 'System', description: 'Full administrative access and security overrides' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    code: 'EMP-001',
    name: 'Imane Benkirane',
    email: 'imane.b@workflow-erp.ma',
    phone: '+212 661-234567',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    role: 'Director',
    title: 'Director of Software Engineering',
    status: 'Active',
    joinDate: '2021-03-15',
    location: 'Casablanca HQ (Marina)',
    permissions: ['emp_read', 'emp_write', 'prj_read', 'prj_write', 'tsk_manage', 'lev_request', 'lev_approve', 'exp_submit', 'exp_approve', 'aud_view', 'sys_admin'],
  },
  {
    id: 'emp-2',
    code: 'EMP-002',
    name: 'Yassine Mansouri',
    email: 'yassine.m@workflow-erp.ma',
    phone: '+212 662-891011',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    role: 'Senior Engineer',
    title: 'Senior Full Stack .NET & React Engineer',
    status: 'Active',
    joinDate: '2022-06-01',
    location: 'Rabat Tech Park',
    managerId: 'emp-1',
    permissions: ['emp_read', 'prj_read', 'tsk_manage', 'lev_request', 'exp_submit'],
  },
  {
    id: 'emp-3',
    code: 'EMP-003',
    name: 'Karim Alami',
    email: 'karim.alami@workflow-erp.ma',
    phone: '+212 663-121314',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Finance & Accounting',
    role: 'Department Manager',
    title: 'Head of Financial Operations',
    status: 'Active',
    joinDate: '2020-11-10',
    location: 'Casablanca HQ (Marina)',
    permissions: ['emp_read', 'exp_submit', 'exp_approve', 'lev_request', 'lev_approve', 'aud_view'],
  },
  {
    id: 'emp-4',
    code: 'EMP-004',
    name: 'Sara Tazi',
    email: 'sara.t@workflow-erp.ma',
    phone: '+212 664-556677',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    role: 'Specialist',
    title: 'People Operations & Talent Lead',
    status: 'Active',
    joinDate: '2023-01-20',
    location: 'Casablanca HQ (Marina)',
    permissions: ['emp_read', 'emp_write', 'lev_request', 'lev_approve', 'exp_submit', 'aud_view'],
  },
  {
    id: 'emp-5',
    code: 'EMP-005',
    name: 'Mehdi Chraibi',
    email: 'mehdi.c@workflow-erp.ma',
    phone: '+212 665-998877',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    role: 'Team Lead',
    title: 'Lead UX/UI Designer',
    status: 'Active',
    joinDate: '2022-09-12',
    location: 'Remote (Tangier)',
    managerId: 'emp-1',
    permissions: ['emp_read', 'prj_read', 'tsk_manage', 'lev_request', 'exp_submit'],
  },
  {
    id: 'emp-6',
    code: 'EMP-006',
    name: 'Salma Berrada',
    email: 'salma.b@workflow-erp.ma',
    phone: '+212 667-334455',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    role: 'Specialist',
    title: 'Logistics & Facility Coordinator',
    status: 'On Leave',
    joinDate: '2023-04-05',
    location: 'Casablanca HQ (Marina)',
    managerId: 'emp-3',
    permissions: ['emp_read', 'lev_request', 'exp_submit'],
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-1',
    code: 'PRJ-101',
    name: 'Azure Cloud ERP Modernization',
    description: 'Migration of legacy business modules to .NET 9 ASP.NET Core Web API with PostgreSQL database and Dockerized container services on Azure Container Apps.',
    department: 'Engineering',
    leadId: 'emp-1', // Imane
    budget: 350000,
    spent: 215000,
    startDate: '2026-06-01',
    deadline: '2026-11-30',
    status: 'In Progress',
    teamIds: ['emp-1', 'emp-2', 'emp-5'],
    progress: 68,
  },
  {
    id: 'prj-2',
    code: 'PRJ-102',
    name: 'Automated Expense Reconciliation Engine',
    description: 'Corporate ledger integration with automated multi-currency receipt parsing, Moroccan tax compliance (TVA/IS), and automated approval routing.',
    department: 'Finance & Accounting',
    leadId: 'emp-3', // Karim
    budget: 120000,
    spent: 84000,
    startDate: '2026-07-15',
    deadline: '2026-10-15',
    status: 'In Progress',
    teamIds: ['emp-3', 'emp-2'],
    progress: 74,
  },
  {
    id: 'prj-3',
    code: 'PRJ-103',
    name: 'HR Portal & Annual Leave Quotas 2027',
    description: 'Self-service portal for staff leave tracking, sickness absence reporting according to Moroccan labor code (Code du Travail), and payroll synchronization.',
    department: 'Human Resources',
    leadId: 'emp-4', // Sara
    budget: 85000,
    spent: 42000,
    startDate: '2026-08-01',
    deadline: '2026-12-15',
    status: 'In Progress',
    teamIds: ['emp-4', 'emp-5'],
    progress: 45,
  },
  {
    id: 'prj-4',
    code: 'PRJ-104',
    name: 'Morocco North Distribution Network Expansion',
    description: 'Opening of new logistics hub in Tangier Med Free Zone, inventory equipment deployment and supply chain workflows.',
    department: 'Operations',
    leadId: 'emp-6',
    budget: 450000,
    spent: 125000,
    startDate: '2026-09-01',
    deadline: '2027-02-28',
    status: 'Planning',
    teamIds: ['emp-6', 'emp-3'],
    progress: 20,
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    code: 'TSK-201',
    projectId: 'prj-1',
    title: 'Implement Entity Framework Core Migrations & Repositories',
    description: 'Configure DbContext for Employee, Expense, Leave and AuditLog entities with PostgreSQL identity schemas and soft deletes.',
    assignedToId: 'emp-2', // Yassine
    priority: 'High',
    status: 'Completed',
    deadline: '2026-09-10',
    createdAt: '2026-08-28',
  },
  {
    id: 'tsk-2',
    code: 'TSK-202',
    projectId: 'prj-1',
    title: 'Configure JWT Auth & Role-Based Authorization Policies in ASP.NET Core',
    description: 'Enforce DepartmentManager, Director, and Employee policy handlers on controllers matching API specification.',
    assignedToId: 'emp-2',
    priority: 'Critical',
    status: 'In Progress',
    deadline: '2026-09-22',
    createdAt: '2026-09-05',
  },
  {
    id: 'tsk-3',
    code: 'TSK-203',
    projectId: 'prj-1',
    title: 'Audit Interceptor Middleware for Change Tracking',
    description: 'Capture modified Entity entries in EF Core SaveChangesAsync to auto-dispatch audit events with client IP and user metadata.',
    assignedToId: 'emp-1', // Imane
    priority: 'High',
    status: 'In Review',
    deadline: '2026-09-18',
    createdAt: '2026-09-02',
  },
  {
    id: 'tsk-4',
    code: 'TSK-204',
    projectId: 'prj-2',
    title: 'Multi-currency VAT Calculation & Exchange Rate Ingestion',
    description: 'Support MAD, USD, EUR transactions with daily Bank Al-Maghrib FX rate syncing.',
    assignedToId: 'emp-3',
    priority: 'Medium',
    status: 'In Progress',
    deadline: '2026-09-25',
    createdAt: '2026-09-08',
  },
  {
    id: 'tsk-5',
    code: 'TSK-205',
    projectId: 'prj-3',
    title: 'Exceptional Leave Category Validator for Moroccan Labor Code',
    description: 'Ensure marriage (4 days), birth (3 days), bereavement (2-3 days) validations pass business rules.',
    assignedToId: 'emp-5',
    priority: 'Medium',
    status: 'Completed',
    deadline: '2026-09-12',
    createdAt: '2026-09-01',
  },
  {
    id: 'tsk-6',
    code: 'TSK-206',
    projectId: 'prj-4',
    title: 'Hardware Procurement RFQ for Tangier Operations Hub',
    description: 'Draft equipment specifications for warehouse barcode scanners, network racks, and staff laptops.',
    assignedToId: 'emp-6',
    priority: 'High',
    status: 'Backlog',
    deadline: '2026-10-05',
    createdAt: '2026-09-14',
  }
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev-1',
    code: 'LEV-089',
    employeeId: 'emp-2', // Yassine
    leaveType: 'Annual leave',
    startDate: '2026-09-28',
    endDate: '2026-10-02',
    daysCount: 5,
    reason: 'Family holiday in Marrakech after project milestone release.',
    status: 'Pending',
    submittedAt: '2026-09-16 10:15',
  },
  {
    id: 'lev-2',
    code: 'LEV-090',
    employeeId: 'emp-6', // Salma
    leaveType: 'Exceptional leave',
    exceptionalSubtype: 'Marriage',
    startDate: '2026-09-15',
    endDate: '2026-09-19',
    daysCount: 4,
    reason: 'Personal wedding ceremonies and family arrangements in Fes.',
    status: 'Approved',
    submittedAt: '2026-09-02 09:30',
    reviewedBy: 'Karim Alami',
    reviewedAt: '2026-09-03 14:10',
    reviewComment: 'Congratulations Salma! Approved as per standard exceptional leave policy.',
  },
  {
    id: 'lev-3',
    code: 'LEV-091',
    employeeId: 'emp-5', // Mehdi
    leaveType: 'Sick leave',
    startDate: '2026-09-11',
    endDate: '2026-09-12',
    daysCount: 2,
    reason: 'Acute seasonal flu, medical certificate from Dr. Bennani provided to HR.',
    status: 'Approved',
    submittedAt: '2026-09-11 08:20',
    reviewedBy: 'Imane Benkirane',
    reviewedAt: '2026-09-11 09:05',
    reviewComment: 'Medical note verified. Rest up and get well soon.',
  },
  {
    id: 'lev-4',
    code: 'LEV-092',
    employeeId: 'emp-2', // Yassine
    leaveType: 'Annual leave',
    startDate: '2026-10-14',
    endDate: '2026-10-16',
    daysCount: 3,
    reason: 'Extended weekend travel.',
    status: 'Pending',
    submittedAt: '2026-09-17 08:30',
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    code: 'EXP-192', // Matches user prompt explicitly!
    employeeId: 'emp-2', // Yassine
    title: 'JetBrains All Products Pack Team Licenses (Annual)',
    amount: 7850,
    currency: 'MAD',
    category: 'Software & Subscriptions',
    date: '2026-09-14',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'jetbrains_invoice_inv2026_9941.pdf',
    status: 'Approved', // Exactly matching prompt example: "Imane changed: Expense #192 Status: Pending → Approved 15 Sep 2026 14:32"
    submittedAt: '2026-09-14 16:20',
    reviewedBy: 'Imane Benkirane',
    reviewedAt: '2026-09-15 14:32',
    managerNotes: 'Approved. Essential development tooling for the .NET 9 modernization team.',
  },
  {
    id: 'exp-2',
    code: 'EXP-193',
    employeeId: 'emp-5', // Mehdi
    title: 'Figma Enterprise Seat Renewal (Q4)',
    amount: 1950,
    currency: 'MAD',
    category: 'Software & Subscriptions',
    date: '2026-09-16',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'figma_receipt_sep2026.pdf',
    status: 'Pending',
    submittedAt: '2026-09-16 11:45',
  },
  {
    id: 'exp-3',
    code: 'EXP-194',
    employeeId: 'emp-3', // Karim
    title: 'Client Strategy Dinner — BMCE Capital Executives',
    amount: 3200,
    currency: 'MAD',
    category: 'Client Dining',
    date: '2026-09-15',
    receiptUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'restaurant_le_cabestan_invoice.pdf',
    status: 'Pending',
    submittedAt: '2026-09-16 09:10',
  },
  {
    id: 'exp-4',
    code: 'EXP-195',
    employeeId: 'emp-2', // Yassine
    title: 'High-speed Fiber Router & Cat6 Cabling for Staging Cluster',
    amount: 1450,
    currency: 'MAD',
    category: 'Hardware & Equipment',
    date: '2026-09-12',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'maroc_bureau_tech_hardware.pdf',
    status: 'Changes Requested',
    submittedAt: '2026-09-13 10:00',
    reviewedBy: 'Imane Benkirane',
    reviewedAt: '2026-09-14 11:20',
    managerNotes: 'Please attach the official tax stamp invoice (Facture avec ICE et identifiant fiscal) before we can process reimbursement.',
  },
  {
    id: 'exp-5',
    code: 'EXP-196',
    employeeId: 'emp-6', // Salma
    title: 'Office Stationery & Ergonomic Monitor Arms (Marina Office)',
    amount: 890,
    currency: 'MAD',
    category: 'Office Supplies',
    date: '2026-09-10',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'bureau_vallee_casablanca.pdf',
    status: 'Approved',
    submittedAt: '2026-09-10 14:00',
    reviewedBy: 'Karim Alami',
    reviewedAt: '2026-09-11 16:30',
    managerNotes: 'Approved for office facilities maintenance budget.',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-1',
    userId: 'emp-1',
    userName: 'Imane Benkirane',
    userRole: 'Director of Software Engineering',
    action: 'Status Changed',
    entity: 'Expense #192',
    entityType: 'Expense',
    oldValue: 'Status: Pending',
    newValue: 'Status: Approved',
    timestamp: '15 Sep 2026 14:32',
    ipAddress: '196.200.145.22',
    notes: 'Approved team software licenses subscription claim.',
  },
  {
    id: 'aud-2',
    userId: 'emp-1',
    userName: 'Imane Benkirane',
    userRole: 'Director of Software Engineering',
    action: 'Requested Changes',
    entity: 'Expense #195',
    entityType: 'Expense',
    oldValue: 'Status: Pending',
    newValue: 'Status: Changes Requested',
    timestamp: '14 Sep 2026 11:20',
    ipAddress: '196.200.145.22',
    notes: 'Requested official ICE/Fiscal ID tax invoice.',
  },
  {
    id: 'aud-3',
    userId: 'emp-3',
    userName: 'Karim Alami',
    userRole: 'Head of Financial Operations',
    action: 'Status Changed',
    entity: 'Leave #090',
    entityType: 'Leave',
    oldValue: 'Status: Pending',
    newValue: 'Status: Approved',
    timestamp: '03 Sep 2026 14:10',
    ipAddress: '196.200.148.91',
    notes: 'Approved Salma Berrada exceptional wedding leave (4 days).',
  },
  {
    id: 'aud-4',
    userId: 'emp-2',
    userName: 'Yassine Mansouri',
    userRole: 'Senior Engineer',
    action: 'Created',
    entity: 'Expense #192',
    entityType: 'Expense',
    oldValue: 'N/A',
    newValue: 'Amount: 7,850 MAD, Category: Software & Subscriptions',
    timestamp: '14 Sep 2026 16:20',
    ipAddress: '105.158.42.114',
    notes: 'Submitted claim with attached JetBrains corporate invoice.',
  },
  {
    id: 'aud-5',
    userId: 'emp-1',
    userName: 'Imane Benkirane',
    userRole: 'Director of Software Engineering',
    action: 'Status Changed',
    entity: 'Task #201',
    entityType: 'Task',
    oldValue: 'Status: In Progress',
    newValue: 'Status: Completed',
    timestamp: '10 Sep 2026 17:45',
    ipAddress: '196.200.145.22',
    notes: 'Entity Framework Core migration verified and merged into main.',
  },
  {
    id: 'aud-6',
    userId: 'emp-4',
    userName: 'Sara Tazi',
    userRole: 'People Operations Lead',
    action: 'Created',
    entity: 'Employee #006',
    entityType: 'Employee',
    oldValue: 'N/A',
    newValue: 'Salma Berrada joined Operations department',
    timestamp: '05 Apr 2026 09:00',
    ipAddress: '196.200.150.12',
    notes: 'Onboarded employee with standard facilities profile.',
  }
];

export const DEMO_USERS: CurrentUser[] = [
  {
    id: 'emp-1',
    name: 'Imane Benkirane',
    email: 'imane.b@workflow-erp.ma',
    role: 'Director',
    department: 'Engineering',
    isManager: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    ip: '196.200.145.22',
  },
  {
    id: 'emp-2',
    name: 'Yassine Mansouri',
    email: 'yassine.m@workflow-erp.ma',
    role: 'Senior Engineer',
    department: 'Engineering',
    isManager: false,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ip: '105.158.42.114',
  },
  {
    id: 'emp-3',
    name: 'Karim Alami',
    email: 'karim.alami@workflow-erp.ma',
    role: 'Department Manager',
    department: 'Finance & Accounting',
    isManager: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ip: '196.200.148.91',
  },
  {
    id: 'emp-4',
    name: 'Sara Tazi',
    email: 'sara.t@workflow-erp.ma',
    role: 'Specialist',
    department: 'Human Resources',
    isManager: true,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    ip: '196.200.150.12',
  }
];
